spring:
  profiles: local
  application:
    name: eureka-ribbon-hystrix
server:
  port: 2501
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

---
spring:
  profiles: dev
  application:
    name: eureka-consumer
server:
  port: 2501
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1002/eureka/,http://peer2:1003/eureka/