#locahost environment config
spring:
  profiles: local
  application:
    name: eureka-server
server:
  port: 1001
eureka:
  environment: local
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

---
#dev environment config
spring:
  profiles: dev1
  application:
    name: eureka-server
server:
  port: 1002
eureka:
  environment: dev
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1003/eureka/
    register-with-eureka: false
    fetch-registry: false
---
#dev environment config
spring:
  profiles: dev2
  application:
    name: eureka-server
server:
  port: 1003
eureka:
  environment: dev
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1002/eureka/
    register-with-eureka: false
    fetch-registry: false