spring:
  profiles: local
  application:
    name: eureka-client
server:
  port: 2002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/


---
spring:
  profiles: dev
  application:
    name: eureka-client
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1002/eureka/,http://peer2:1003/eureka/