spring:
  profiles: local
  application:
    name: eureka-consumer
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

---
spring:
  profiles: dev
  application:
    name: eureka-consumer
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1002/eureka/,http://peer2:1003/eureka/